### ISSUE TITLE
docs: list of methods

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#103]
*Should we include a list of methods* at the end of `execution_workflows/README.md`, that can be linked to in the presentation (and for documentation).    
Possibly useful columns:
- Method name
- link to publication
- link to repository
- type (identification, quantification, differential usage)
- status in APAeval (ready, in progress, to do, on hold, dismissed, etc.) (check PRs, issues, slack execution_workflows)
- present in OEB (Yes/No)
- installation (Bioconductor, bioconda, ...?)
- ~Notes (don't know, e.g. R based, using DESeq, only method that can take your dog for a walk)~
- can take your dog for a walk (Yes/No/depends)

**Comment by uniqueg** [comment]
Great idea and good suggestion on the columns. One comment though: I would leave out the *Notes*. Guess having worked with schemas and specs for a while now, I started to loathe unstructured data a bit 😆 But really though, notes/comments cause tables to look horrible and it's always subjective. It may also be inaccurate, e.g., you'd need to know all methods to know if yours is the only one that can take your dog for a walk. And if taking your dog for a walk is a thing, it might make more sense to add it as a separate column. So my proposal: replace *Notes* with *Can take your dog for a walk?*

**Comment by chelseaherdman** [comment]
Sounds great! I can work on this later today if the methods team can answer the last columns (status in APAeval, in OpenEBench, Installation and Can take your dog for a walk.

**Comment by ninsch3000** [comment]
OEB status is in the spreadsheet. It's what @FitzsimmonsCM had been working on before the hackathon

**Comment by uniqueg** [comment]
Guess for the last column, we can have a defined vocabulary like this, and you can pick random for each method:

* Probably not
* Maybe
* Only if you ask nicely
* No, and neithe could my dog walk _it_
* No way
* Nope
* No, but it can take _you_ for a ride
*

**Comment by FitzsimmonsCM** [comment]
I can check again to see if any new additions to OEB were made in the last few days. But that column should be fairly up-to-date as of 25 May.

**Comment by FitzsimmonsCM** [comment]
OEB pages for aptardi ( #30 ) and LABRAT( #35) are now on OEB. The OEB links were added to the google sheet. 

CSI-UTR, APAtrap, DaPars, and DaPars2 are not yet on OEB.
