### ISSUE TITLE
OpenEBench summary workflow: Fix _id of aggregation

### ISSUE THREAD

**Issue by AsierGonzalez** [iRNA-COSI/APAeval#153]
The `_id` of the aggregation object contains two hardcoded parts that are outdated. Although they do not cause any issues, it would be good for them to have meaningful and updated values.

This value is given in [line 83 of manage_assessment_data.py](https://github.com/yuukiiwa/APAeval-summary-workflow/blob/master/benchmarking_dockers/apaeval_consolidation/manage_assessment_data.py#L83):

```
"_id": "TCGA:{}_{}_Aggregation".format(DEFAULT_eventMark, challenge),
```

- Instead of "TCGA", it should have the id of the community as it happens with the assessments that are included in the same output file. Looking in main.nf It [doesn't look like the name/id of the this value is passed to this script as an argument](https://github.com/yuukiiwa/APAeval-summary-workflow/blob/452b263b9e96b084c43b20c6ca2712f3c3c918e0/main.nf#L145) as it does with the[ call to compute_metrics.py](https://github.com/yuukiiwa/APAeval-summary-workflow/blob/452b263b9e96b084c43b20c6ca2712f3c3c918e0/main.nf#L125) so it would probably need to be added. Another (suboptimal) solution would be to hardcode `APAeval` in there.
- The variable `DEFAULT_eventMark` embedded in the id [is defined in the script](https://github.com/yuukiiwa/APAeval-summary-workflow/blob/master/benchmarking_dockers/apaeval_consolidation/manage_assessment_data.py#L12) and it contains a date - currently `2018-04-05`. This date should be shared by all the runs of the same tool, so it is a configuration parameter that should probably go in main.nf. Again, as a temporary solution it could be hardcoded to something like '2021-06-04'.

**Comment by AsierGonzalez** [comment]
After checking how the workflows are integrated in the OpenEBench framework I suggest that we go for the simple solution of replacing "TCGA" with "APAeval" in the code, as trying to use the `community_id` variable has some unwanted consequences that require further changes.

Same for the date, just update it with a more current date of your choice.

**Comment by yuukiiwa** [comment]
Thanks, Asier! I have changed `TCGA` to `APAeval` and the data to 2021-06-04: https://github.com/yuukiiwa/APAeval-summary-workflow/commit/78930e05d0903d2245e2668529eaa93a9c178de7

**Comment by AsierGonzalez** [comment]
Fantastic, thank you @yuukiiwa!

**Comment by AsierGonzalez** [comment]
The changes had the desired effect - I'm closing the ticket. Thank you for the great work @yuukiiwa!
