### ISSUE TITLE
Execution Workflow: APAlyzer

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#19]
## WHAT    
**Write** execution workflow for [APAlyzer](https://bioconductor.org/packages/release/bioc/html/APAlyzer.html). Use the provided [small files for testing](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data) (running the workflow on real data is a different issue).

## CHECKLIST   
* [x] Use [snakemake template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/snakemake) or [nextflow template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/nextflow) to create your workflow.
* [x] Comment your code
* [x] Run individual rules/processes in either conda envs or docker/singularity containers for reproducibility
* [x] Input:  .bam or .fastq from [`test_data`](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data)
* [ ] Give [feedback about the method](https://forms.gle/mAAkbRJqhedJnSeJ6)

## OUTPUTS (see [specification](https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/execution_output_specification.md)): 
* [x] ~Output: Adhere to output specification for Identification challenge~ (No identification)
* [x] ~Output: Adhere to output specification for quantification challenge~ (No quantification)
* [x] Output: Adhere to output specification for differential usage challenge
   > This TSV file contains two columns:

    > - gene ID
    > - significance of differential PAS usage

    > Column names should not be added to the file.

**Comment by mkatsanto** [comment]
I have created the following branch https://github.com/iRNA-COSI/APAeval/tree/apalyzer
APAlyzer implementation is currently stuck since the creation of a reference genome based on a given gtf is not working for this tool. You currently have to rely on predefined PAS atlas, which is not reliable for the benchmark.
I opened an issue in the git repo of the tool (https://github.com/RJWANGbioinfo/APAlyzer/issues/7) and await further info.

**Comment by SamBryce-Smith** [comment]
@mkatsanto looks like [issue you've reported](https://github.com/RJWANGbioinfo/APAlyzer/issues/7) has been fixed. Are you still able to carry on with completing this workflow (looks like you've done a lot already!) or should we consider this workflow open for other contributors?

Thanks :)

**Comment by SamBryce-Smith** [comment]
Hey @mkatsanto, do you think you'll find the time to finish this off over the next couple of weeks or should I reassign the workflow to someone else?

**Comment by mkatsanto** [comment]
Hi! Sorry for the late reply! I will try in the next week to resolve it . If someone wants to also take a try or work also on this, it is fine by me.

**Comment by SamBryce-Smith** [comment]
Hey @mkatsanto, just a gentle bump on this workflow. We've got a deadline of 30th September for getting the execution workflows merged, do you think you'll have time to finish it off?
