### ISSUE TITLE
Docker image for QAPA missing

### ISSUE THREAD

**Issue by dominikburri** [iRNA-COSI/APAeval#194]
It appears that the Docker image for QAPA is missing.
The `execution_workflows/QAPA/README.md` of QAPA is describing that the software has to be manually installed. 
However, as described in the execution workflow readme, we require Docker images. 

Therefore, as described in `execution_workflows/README.md`:

- [x] check if Docker image available
and if not:
- [x] build Docker image based on Dockerfile
- [x] upload image to Dockerhub
- [x] Specify Docker image in workflow

**Comment by yuukiiwa** [comment]
Hi @dominikburri, the docker image is available on Docker Hub: https://hub.docker.com/r/apaeval/qapa. I will create a PR for adding the QAPA `Dockerfile` to the QAPA repository when I also update the nextflow documentation on the execution flags. Here is the content of the QAPA Dockerfile:
```
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base python3 python3-setuptools python3-dev python3-pip

RUN apt-get install bedtools

COPY . /qapa
WORKDIR /qapa

RUN Rscript /qapa/scripts/install_packages.R

RUN python3 /qapa/setup.py install

ENTRYPOINT ["qapa"]
```
The Docker image is specified in the following modules: [qapa_index.nf](https://github.com/iRNA-COSI/APAeval/blob/b6f2ebc3cc21fa27a1d197e4ee2ab6717d8b3305/execution_workflows/QAPA/modules/qapa_index.nf#L10) and [qapa_quant.nf](https://github.com/iRNA-COSI/APAeval/blob/b6f2ebc3cc21fa27a1d197e4ee2ab6717d8b3305/execution_workflows/QAPA/modules/qapa_quant.nf#L10)
Thanks!

**Comment by dominikburri** [comment]
Ah I didn't see those files, I was just checking the readme. Adding the dockerfile would be great, thank you! 
And if you could also describe that the Docker image is available in the readme would be great as well.
