### ISSUE TITLE
Parsing output with wrong cast to string

### ISSUE THREAD

**Issue by dominikburri** [iRNA-COSI/APAeval#207]
https://github.com/iRNA-COSI/APAeval/blob/e581d3ffc844961edbc2efd701cc440c4b361709/execution_workflows/DaPars/bin/convert_output.py#L38

The line above leads to an erroneous return statement in this line: https://github.com/iRNA-COSI/APAeval/blob/e581d3ffc844961edbc2efd701cc440c4b361709/execution_workflows/DaPars/bin/convert_output.py#L45

The problem is the cast of the value to `str`, which results in a wrong evaluation of `min`.

Take the example below:
```
sign = [str(1.0), str(0.499), str(0.144), str(7.136e-21)]
min(sign)
```
will give '0.144' instead of the minimum of `7.136e-21`

This can be avoided by casting to **float** (or no casting):
```
sign = [float(1.0), float(0.499), float(0.144), float(7.136e-21)]
min(sign)
```
will give the correct result `7.136e-21`

**Comment by faricazjj** [comment]
Thanks so much for catching this @dominikburri ! I'll create a PR to fix this :)
