### ISSUE TITLE
bug: swf validation will fail with gencode "chr" format

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#240]
https://github.com/iRNA-COSI/APAeval/blob/defa466db6d6e3a52f6b30ad18dda63a3b0a6d08/summary_workflows/quantification/quantification_dockers/q_validation/validation.py#L64-L69

This only works with ensembl chromosome format (e.g. "1"), not with Gencode (e.g. "chr1"). As APAeval uses Gencode format this needs to be fixed.     
The whole validation should be re-designed, as the participant input format has to match the ground truth/gtf format.    

Remember to edit this in all existing swfs.

**Comment by ninsch3000** [comment]
UPDATE: we have been confirming today with @txellferret that we can also load the ground truth and gtf files in the validation step, so the correct input format can be inferred from gt & gtf. (all three files need same chromosome naming scheme, else fail.

**Comment by ninsch3000** [comment]
Please have a look at PR #238 to check out how we're planning to pass the gtf annotations to the nextflow workflow. Adapt the validation step correspondingly.

**Comment by dominikburri** [comment]
Implemented in PR #238, closing now.
