### ISSUE TITLE
feat: use annotation files in summary workflows

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#241]
Currently, only the participant input and the ground truth file (=challenge) are loaded into the nextflow workflow. For the calculation of some metrics it is however necessary to also load the annotation (gtf). For local runs the path to this file can be specified in the config, depending on which organism the challenge belongs to. For the OEB VRE some changes are necessary, to infer the annotation file path from the challenge name. Challenge names thus *MUST* contain organism information in the form of `hg` or `mm`

will be fixed in #238

**Comment by dominikburri** [comment]
As mentioned, fixed in #238, so closing here.
