### ISSUE TITLE
feat: pass ranking information in summary workflow

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#242]
Currently the top-right corner of all output 2D-plots is considered the "best" corner. This has to be changed for some metrics/plots.
As there are only the two options "top-right" or "bottom-right" available, the axes of some plots might have to be reconsidered. 

For all summary workflows the following files have to be adapted:
1. `aggregation_template.json`  
Include `optimization` parameter in the `visualization` object as follows:
```
"visualization": {
            "type": "2D-plot",
            "x_axis": "expression_unmatched",
            "y_axis": "correlation",
            "optimization": "bottom-right"
        }
```

2. `assessment_chart.py`:
 `better` variable is hardcoded ([https://github.com/iRNA-COSI/APAeval/blob/defa466db6d6e3a52f6b30ad18dda63a3b0a6d08[…]on_dockers/q_consolidation/assessment_chart/assessment_chart.py](https://github.com/iRNA-COSI/APAeval/blob/defa466db6d6e3a52f6b30ad18dda63a3b0a6d08/summary_workflows/quantification/quantification_dockers/q_consolidation/assessment_chart/assessment_chart.py#L278)), can be read from passed aggregation object (if changes as described in 1. have been made) as follows:

```
better = aggregation_file["datalink"]["inline_data"]["visualization"]["optimization"]
```

3. Change specifications and corresponding metric computations if necessary.

**Comment by dominikburri** [comment]
Thanks @ninsch3000 for pointing this out! 

As @txellferret explained me, all 4 corners can be specified, so *top-right*, *top-left*, *bottom-right* and *bottom-left*.
So I don't think we need to re-consider the specifications.

The bar-plots do not have the optimisation parameter, but it could be implemented if we need it.
