### ISSUE TITLE
docs: Update participant table

### ISSUE THREAD

**Issue by dominikburri** [iRNA-COSI/APAeval#257]
The table in the execution workflow readme contains a table with all participants: https://github.com/iRNA-COSI/APAeval/blob/437252a5af58dea7882f4bb4190aca4b67f214f8/execution_workflows/README.md?plain=1#L120

It should be updated:

- [x] remove the last column (with the dog) as it is leftover from initialisation.
- [x] ensure "Type" is up-to-date. That is, does it perform the given type in this repo? 
- [x] column "Installation" could be extended with whether Docker image is up and running. Or put in a new column. 

I probably missed something, so please add anything missing!
Most information can simply be used from our dedicated google table.

**Comment by ninsch3000** [comment]
Fixed in #464
