### ISSUE TITLE
bug: python object passed as reference

### ISSUE THREAD

**Issue by dominikburri** [iRNA-COSI/APAeval#305]
https://github.com/iRNA-COSI/APAeval/blob/c9e40a9672d5b98e7f6fc2c4c3aa6d7fc18c0fcb/summary_workflows/quantification/quantification_dockers/q_metrics/matchPAS/matchPAS.py#L54

The function obtains variable `matched_sites` but it appears the global variable is used and thus the results are not valid (seen as exceptionally high TPM values for certain PAS, because the same first two rows are used for the same object within the lambda statement in line 89). 

The fix could involve calling the function in line 48 with `matched_sites_new` and adding `matched_sites = matched_sites_new.copy()` prior to line 54. 

Maybe this also happens in other functions, like lines 67, 101, 179, but not sure.

**Comment by ninsch3000** [comment]
Check whether the effect described [here](https://apaeval.slack.com/archives/C01PHLQKNH0/p1654219600609689 ) is resolved upon bug fix. (Better corr for larger window sizes?)

**Comment by dominikburri** [comment]
Hi @ninsch3000, I encountered the described behaviour with real data for which certain PAS would get multiple of TPMs values from the input BED file. 
Maybe this doesn't happen here with the small example. Based on your reports, it looks fine.
Also, the function `find_weights` is called within `split_pd_by_dist`, which is for the case of one PD site and two GT sites.
