### ISSUE TITLE
Scientific Manuscript: Data summary table

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#306]
Using the [MultiQC reports from the preprocessing with nf-core/rnaseq](https://drive.google.com/drive/folders/1NBNPRTTaMwWttx4Ua4ZuA3uIj_NSd0w5), a [table to describe the different input datasets](https://docs.google.com/document/d/1ZkA4PvPPHXMFlmZNLr0qCL18xnXWo-W5tZrPiyIq2_o/edit?disco=AAAAbewQp1s) can be created.    
Interesting aspects are among others
- lib sizes
- biotypes
- genomic origin/RseqC read distribution

Such a description of the data might also come in handy in the discussion of the results (e.g. which tools handle intronic PAS well, does lib size influence performance, etc)

**Comment by mrgazzara** [comment]
I'm unblocking this issue. I've resolved the issues with strandedness on the two flagged datasets mentioned in #302. The MultiQC data uploaded to the [GDrive directory](https://drive.google.com/drive/folders/1NBNPRTTaMwWttx4Ua4ZuA3uIj_NSd0w5) is now using the correct strandedness (only MmusCortex changed). Notes on why I think the GTEXsim is really `forward` stranded and not `unstranded` as MultiQC flags it are documented under [this subheading](https://docs.google.com/document/d/1kUo839artWBhdMFTmPfAS4U0hzq_yj3xF6GDQwuKtFY/edit#heading=h.2mghng6cu4zf) in my [GDoc](https://docs.google.com/document/d/1kUo839artWBhdMFTmPfAS4U0hzq_yj3xF6GDQwuKtFY/edit?usp=sharing) specifying mapping parameters.

@ninsch3000 mentioned in today's sync meeting that while we could move forward and start gathering results from this analysis now, we will probably wait a bit for initial APA quantification benchmark results to come in so we can identify which datasets, biotypes, etc. seem most worth looking into (e.g. Mayr immune cell datasets may have lots of Intronic PolyA and the mapping statistics show that, etc.)
