### ISSUE TITLE
Community manuscript: Revise current outline and content

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#307]
@FitzsimmonsCM and @chelseaherdman created an outline of the community manuscript with bullet points of content to be added for each section

Todo:
Revise current outline and content
Finalize structure and points for each section
Decide on how to break the manuscript down into smaller, trackable tasks
Currently, there are placeholder issues that should be edited/deleted/added based on the final tasks decided:
Draft abstract: https://github.com/iRNA-COSI/APAeval/issues/279
Draft background: https://github.com/iRNA-COSI/APAeval/issues/280
Draft main sections: https://github.com/iRNA-COSI/APAeval/issues/281
Draft discussion: https://github.com/iRNA-COSI/APAeval/issues/282
Draft supplementary material: https://github.com/iRNA-COSI/APAeval/issues/283
Prepare for submission: https://github.com/iRNA-COSI/APAeval/issues/284

**Comment by uniqueg** [comment]
Meta issue for each individual subtasks were created in #335. Leaving this issue open until all foreseeable subtasks were added.
