### ISSUE TITLE
Scientific Manuscript Writing: Methods Section

### ISSUE THREAD

**Issue by FitzsimmonsCM** [iRNA-COSI/APAeval#318]
- [ ] Expand metrics section: (e.g. explain correlation vs number of unmatched, why did we choose certain metrics over others?)
- [ ] Update final list of methods included in our workflows
- [ ] Expand data set selection (e.g. how were these chosen? What is an 'ideal' data set? Are data sets linked in any way?)

**Comment by faricazjj** [comment]
I'm adding Matt here to help with dataset and metric info! :D
