### ISSUE TITLE
Quantification summary workflow: Include all considered metrics

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#324]
Credits to @ninsch3000 for putting together this list of suggested metrics by @mrgazzara , @dominikburri , @SamBryce-Smith ,  @ninsch3000, and @daneckaw 

We decided to add calculation of all considered metric so it'd be more convenient to pick which final metric to include in OpenEBench, or for changes in the future.

Metrics to be included are:
- Correlation: spearman and pearson : https://github.com/iRNA-COSI/APAeval/issues/326
- Number of unmatched sites and percent (un)matched: https://github.com/iRNA-COSI/APAeval/issues/327
- include without unmatched sites option (correlation will be much better): https://github.com/iRNA-COSI/APAeval/issues/325

More to be added as needed, more discussions needed, e.g.   
- Is the matching of predicted and ground truth PAS ideal, or has the splitting/merging of sites to be revisited? 
This question arose because for the preliminary results, correlations were higher for smaller window sizes, and not as would be naively expected for larger ones.

We discussed that we could potentially get identification summary workflow results from quantification using match_with_gt function which returns the table with matched and unmatched sites of ground truth and predicted that we can use to directly calculate identification metrics. Identification metrics to include:
- Sensitivity/Recall
- Precision
More to be added

**Comment by dominikburri** [comment]
*F1 score* as the harmonic mean of precision and sensitivity could be added.

**Comment by ninsch3000** [comment]
Has been discussed in metrics meeting, nothing to add here, presented suggestions will be fixed with #379
