### ISSUE TITLE
Execution Workflow: GETUTR

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#33]
## WHAT    
**Write** execution workflow for [GETUTR](http://big.hanyang.ac.kr/GETUTR/manual.htm). Use the provided [small files for testing](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data) (running the workflow on real data is a different issue).

## CHECKLIST   
* [ ] Use [snakemake template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/snakemake) or [nextflow template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/nextflow) to create your workflow.
* [ ] Comment your code
* [ ] Run individual rules/processes in either conda envs or docker/singularity containers for reproducibility
* [ ] Input:  .bam or .fastq from [test_data]((https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data))
* [ ] Give [feedback about the method](https://forms.gle/mAAkbRJqhedJnSeJ6)

## OUTPUTS (see [specification](https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/execution_output_specification.md)): 
* [ ] Output: Adhere to output specification for Identification challenge
     > This BED file contains single-nucleotide position of poly(A) sites identified by the tool.
Fields:

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - not used, leave as "."
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for quantification challenge
     > This BED file contains positions of unique poly(A) sites with TPM values for each identified site in the score column.

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - TPM value for the identified site
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] ~Output: Adhere to output specification for differential usage challenge~ No differential usage

**Comment by grexor** [comment]
GETUTR looks to be using python2.x, having problems installing rpy2 (one of the requirements):

`pip2.7 install rpy2`

Collecting rpy2
  Downloading rpy2-3.5.2.tar.gz (202 kB)
     |████████████████████████████████| 202 kB 6.8 MB/s 
    ERROR: Command errored out with exit status 1:
    rpy2 is no longer supporting Python < 3.7.Consider using an older rpy2 release when using an older Python release.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by grexor** [comment]
Ok trying to make it work in a clean Docker install with python2.7
