### ISSUE TITLE
Refactor quantification summary workflow metric variable names and description

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#333]
Currently, as we added new metric calculations and results for quantification summary workflow, the metric names are getting longer. For example, Correlation_coefficient_Pearson_.... could be changed to Pearson_r. A description of what each metric calculates and represents should also be added in the readme to avoid confusion down the line with more metrics added.

In summary:
- Make metric variables shorter
- Add descriptions for metrics

See PR comment for initial discussion for this: https://github.com/iRNA-COSI/APAeval/pull/328

**Comment by ninsch3000** [comment]
* [ ]  re-phrase the metric name for `percent_unmatched` to reflect that this is referring to expression (%TPM)

**Comment by ninsch3000** [comment]
In order to group functions/modules logically, issue #374 has to be solved.
