### ISSUE TITLE
Execution Workflow: IsoSCM

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#34]
## WHAT    
**Write** execution workflow for [IsoSCM](https://github.com/shenkers/isoscm). Use the provided [small files for testing](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data) (running the workflow on real data is a different issue).

## CHECKLIST   
* [ ] Use [snakemake template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/snakemake) or [nextflow template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/nextflow) to create your workflow.
* [ ] Comment your code
* [ ] Run individual rules/processes in either conda envs or docker/singularity containers for reproducibility
* [ ] Input:  .bam or .fastq from [test_data]((https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data))
* [ ] Give [feedback about the method](https://forms.gle/mAAkbRJqhedJnSeJ6)

## OUTPUTS (see [specification](https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/execution_output_specification.md)): 
* [ ] Output: Adhere to output specification for Identification challenge
     > This BED file contains single-nucleotide position of poly(A) sites identified by the tool.
Fields:

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - not used, leave as "."
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Does IsoSCM perform PAS quantification? If yes:
* [ ] Output: Adhere to output specification for quantification challenge
     > This BED file contains positions of unique poly(A) sites with TPM values for each identified site in the score column.

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - TPM value for the identified site
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for differential usage challenge
   > This TSV file contains two columns:

    > - gene ID
    > - significance of differential PAS usage

    > Column names should not be added to the file.

**Comment by chilampoon** [comment]
Ran into the same issue described here https://github.com/shenkers/isoscm/issues/12

Need the + or - strand information stored as XS tags in the BAM files, which are currently absent in the test data

**Comment by SamBryce-Smith** [comment]
Hey @chilampoon 

Just wanted to check if you're still going to be able to contribute to this workflow? Absolutely not a problem if not (though would be great if you still want to help out!), it's mainly so the rest of the group know what still needs to be done. 

Also, if you've managed to make any progress so far it would be great to see any of your code pushed, even if it's still a work in progress due to issue you mentioned above. Most of all you'll get credit for your work but then others can join in too without starting from scratch. 

Thanks :)

**Comment by chilampoon** [comment]
Hi @SamBryce-Smith ! Yep I was intended to finish this one at some point but haven't started..., need 1 or 2 days or so. When is the deadline?

**Comment by SamBryce-Smith** [comment]
That's great @chilampoon! No deadline at this point, we just wanted to know if we could consider the workflow as still in progress or whether it needed to be re-assigned :)
