### ISSUE TITLE
[CommBench: Publishing] Compile author information

### ISSUE THREAD

**Issue by uniqueg** [iRNA-COSI/APAeval#357]
Compile table of all authors, including:
- [ ] Full names (as they should appear on the paper)
- [ ] Email addresses
- [ ] ORCIDs
- [ ] Funding information
- [ ] Conflict of interest assertions
- [ ] Contributions to this manuscript (ideas, text, figures, tables, templates, etc.)
- [ ] Declared funding
- [ ] Agreement to be listed as author

**Depends on:**
- #336

**Comment by faricazjj** [comment]
@FitzsimmonsCM do you want to pick this up since you already have some information on this already for the scientific manuscript? :D

**Comment by FitzsimmonsCM** [comment]
Hi @uniqueg and @faricazjj  I have a list of most of this information for the scientific manuscript!

**Comment by uniqueg** [comment]
Fantastic, that will be very useful, @FitzsimmonsCM. Perhaps you could just create a copy of the table as another tab in the same sheet? We could then go through that second list when the manuscript is close to completion and confirm contributors
