### ISSUE TITLE
Summary workflows: Control code duplication

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#374]
## Problem
We have 3 distinct benchmarking events, each of which has its own summary (=benchmarking) workflow. These [summary workflows](https://github.com/iRNA-COSI/APAeval/tree/main/summary_workflows) are very similar to each other and only differ in a couple of functions. Each workflow consists of 3 steps, each of which is run in a separate docker container. The containers are built separately for each of the 3 steps for each of the 3 events, from Dockerfiles residing in a directory structure as described below. The 3 events do share some functions though, which we need to keep synchronized across events. In the current implementation, we keep copy-pasting the functions between events whenever they change, which will inevitably cause inconsistencies at some point.
```
summary_workflows
    |-- event_A
        |-- step_1
            |-- Dockerfile
            |-- requirements.txt
            |-- script_1A
            |-- module_X
                 |-- function_X
        |-- step_2
            |-- Dockerfile
            |-- requirements.txt
            |-- script_2A
            |-- module_Y
                 |-- function_Y
        |-- step_3
          .....
    |-- event_B
        |-- step_1
            |-- Dockerfile
            |-- requirements.txt
            |-- script_1B
            |-- module_X
                 |-- function_X
        |-- step_2
            |-- Dockerfile
            |-- requirements.txt
            |-- script_2B
            |-- module_Y
                 |-- function_Y
        |-- step_3
          .....
    |-- event_C
          .....
```
While the basic structures of script_1A and script_1B are similar, they do have event specific adaptations, so I suppose we can't do much better than duplicating the code. However, module_X really is the same in both events and we want to keep it synchronized.     
If we understand correctly, docker requires files to be included in a container to reside inside the _build context_ 

> (see [here](https://docs.docker.com/engine/reference/builder/#add), "The <src> path must be inside the context of the build; you cannot ADD ../something /something, because the first step of a docker build is to send the context directory (and subdirectories) to the docker daemon.")   

so that's why we haven't moved `module_X` to the `summary_workflows` directory level.     

### _How can we keep `module_X` synchronised between events?_   
And: is there really nothing we can do for `script_1A` and `script_1B`?

## Possible solutions?
1. Circumvent the above described docker requirement?
  Would [the single file archive suggested in the first answer here](https://stackoverflow.com/questions/37789984/how-to-copy-folders-to-docker-image-from-dockerfile) work/make sense?
2. Add `module_X` to PyPi and `requirements.txt`?
   How much work is this, especially in case we need to update `module_X` frequently?
3. Use [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?
   How much work is this and how robust is it? Can the containers be built smoothly with that approach?
4. Do something better?
   What?

**Comment by faricazjj** [comment]
@ninsch3000 Talked to Paul about this! Paul is off this week starting from tomorrow but he'll take a look today and plan to work on it when he comes back to work :D

**Comment by ninsch3000** [comment]
see branch paul-code-deduplication
