### ISSUE TITLE
Summary workflow: new metric Jaccard index

### ISSUE THREAD

**Issue by dominikburri** [iRNA-COSI/APAeval#375]
As discussed, we want to add new metrics measuring the similarity of prediction and ground truth PAS sites. 

The [Jaccard index](https://en.wikipedia.org/wiki/Jaccard_index) can be used for this, as it measures the similarity between two sets and is defined as size of the intersection divided by the size of the union of the two sets. 

As for the identification metrics we compute metrics based on binary classifications, i.e. number of true positives TP, false negatives FN and false positives FP, so I suggest to interpret Jaccard index in this regard and would define it as:
```
J(PD, GT) = TP / (TP + FP + FN)
```
where PD is the table of PAS site predictions and GT the table of ground truth PAS sites. Actually, see section *Similarity of asymmetric binary attributes* in above wiki link, the same is described. 

Alternatively or additionally, we could report the dissimilarity with the Jaccard distance, which is `1 - J(PD, GT)`.

**Comment by mrgazzara** [comment]
Thanks for opening the issue. This looks good, @dominikburri. As for using the Jaccard index versus distance, I guess it is a question of if we want the OEB graphs for something like correlation vs. similarity or dissimilarity. Do we want the "best" algorithms in the upper left quadrant (correlation v. Jaccard Index) or upper right quadrant (correlation v. Jaccard distance)?

**Comment by ninsch3000** [comment]
@mrgazzara , shouldn't the "best" corners be the other way around?
will be fixed in #379
