### ISSUE TITLE
Execution Workflow: TAPAS

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#39]
## WHAT    
**Write** execution workflow for [TAPAS](https://github.com/arefeen/TAPAS). Use the provided [small files for testing](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data) (running the workflow on real data is a different issue).

## CHECKLIST   
* [ ] Use [snakemake template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/snakemake) or [nextflow template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/nextflow) to create your workflow.
* [ ] Comment your code
* [ ] Run individual rules/processes in either conda envs or docker/singularity containers for reproducibility
* [x] Input:  .bam or .fastq from [test_data]((https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data))
* [x] Give [feedback about the method](https://forms.gle/mAAkbRJqhedJnSeJ6)

## OUTPUTS (see [specification](https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/execution_output_specification.md)): 
* [ ] Output: Adhere to output specification for Identification challenge
     > This BED file contains single-nucleotide position of poly(A) sites identified by the tool.
Fields:

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - not used, leave as "."
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for quantification challenge
     > This BED file contains positions of unique poly(A) sites with TPM values for each identified site in the score column.

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - TPM value for the identified site
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for differential usage challenge
   > This TSV file contains two columns:

    > - gene ID
    > - significance of differential PAS usage

    > Column names should not be added to the file.

**Comment by SamBryce-Smith** [comment]
Hey @yoseopyoon 

Just wanted to check if you're still going to be able to contribute to this workflow? Absolutely not a problem if not (though would be great if you still want to help out!), it's mainly so the rest of the group know what still needs to be done.

Also, if you've managed to make any progress so far it would be great to see any of your code pushed, even if it's still a work in progress! Most of all you'll get credit for your work but then others can join in too without starting from scratch.

Thanks :)

**Comment by yoseopyoon** [comment]
Hi Sam, 

Thanks for contacting me. Since I am an RNA biologist with poor background in bioinformatics, I think it would be better to have someone else to continue work on this issue. 
However, I am willing to contribute to other areas such as manuscript, literature search etc. 

I don’t have any code to push; below is what I tried during APAeval:
	• I installed TAPAS, figured out how to run it using our small sample data set
	• Troubleshooted converting our test annotation file to refFlat and found it requires “NM_” identifier to be run by the command. Etc.
	• I updated TAPAS section of methods summary spreadsheet and also uploaded TAPAS results from our small test data 
	• Submitted feedback about the method


Thank you !!

Best,

Yoseop 






Yoseop Yoon, Ph.D. 
Postdoctoral Scholar
Shi Lab
Department of Microbiology & Molecular Genetics
School of Medicine
University of California, Irvine

**Comment by yuukiiwa** [comment]
Hi @SamBryce-Smith, I will be taking over the TAPAS execution workflow. Thank you so much for all your effort, @yoseopyoon!

**Comment by SamBryce-Smith** [comment]
## Update on the progress of TAPAS execution workflow

@yuukiiwa implemented a nextflow pipeline on branch `TAPAS`. When trying to run with test data (i.e. much smaller than a typical dataset), the workflow exited with a 137 error code (out of memory error code). See screenshot below & attached `nextflow.log` for this run.

![Screenshot 2022-05-13 at 4 54 46 PM](https://user-images.githubusercontent.com/49978382/168780778-afd41394-be5c-480b-8ed4-b3cc0ed56920.png)

[nextflow.log](https://github.com/iRNA-COSI/APAeval/files/8707101/nextflow.log)

This workflow is currently on hold whilst we focus on other aspects of the challenge, but we may return to this to try and debug (other APA tools/papers have managed to get it running).

**Comment by faricazjj** [comment]
@yuukiiwa @SamBryce-Smith thank you guys for all the work!! Are we planning to create a PR for TAPAS branch to be merged to main?
