### ISSUE TITLE
[Bug Fix] IsoSCM identification output should be from compare step

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#429]
Currently, we get results for identification challenge from one of the output files from the _assemble_ step. Initially, this file seems to contain the identified changepoints just by looking at the content of the file.
![Screen Shot 2022-07-26 at 11 32 38 AM](https://user-images.githubusercontent.com/25573986/181048130-0b5a8dda-ed7f-420b-aafa-33b5a9c2521e.png)

But as I read further beyond the assemble step, the second step they describe is the _compare_ command. The _compare_ command "reports the differential usage of each identified change-point", which I expected to show the site usages of the same sites as the sites from the previous _assemble_ step shown in the screenshot above. But I see less and also different sites in the _compare_ step output file
![Screen Shot 2022-07-26 at 11 35 09 AM](https://user-images.githubusercontent.com/25573986/181048630-6d280fa3-6d08-43d4-957e-a2e174511ab1.png)

This led me to look more into whether we should be extracting sites for identification challenge from the _assemble_ or _compare_ step.

As additional context, the steps to run isoscm are:
1. run _assemble_ step which creates a tmp folder: isoscm/tmp/{sample}.cp.filtered.gtf
2. run _compare_ step, this requires the xml file output from assemble step for two samples, but since we're getting site usage per sample, I put the same sample twice as input to obtain the following output:
![Screen Shot 2022-07-26 at 12 18 54 PM](https://user-images.githubusercontent.com/25573986/181058458-a4aee997-b59a-4a74-8dbd-13f6b336a21e.png)

Even though the first isoscm/tmp/{sample}.cp.filtered.gtf file contains changepoint locations, I'm not entirely sure we should obtain identification output sites from there since it's in a tmp folder and the github readme doesn't explain what the files in the tmp folders are--they only explained the files outside of the tmp folder from _assemble_ step i.e they explained the files from step 2 above but not files from step 1. I think the sites for identification might have to be obtained from the _compare_ step output (i.e. isoscm/compare/{sample}.txt). After reading their readme, I checked their paper and saw that in their paper, they didn't mention _assemble_ step to be where we get identified changpoints. They mentioned from "...Using the “assemble” keyword IsoSCM will assemble the mapped reads in a BAM file into a splice graph, identify nested terminal exons boundaries using the constrained segmentation procedure, and report the resulting models in GTF format....Pairwise comparison of tandem isoform usage can be performed using the “compare” keyword, which reports the relative usage of change points in each sample in a tabular format." 

Hence, it sounds like the _compare_ step outputs the identified change points (or PAS) that we want to report.

**Comment by mrgazzara** [comment]
See full comment on the PR 431 (https://github.com/iRNA-COSI/APAeval/pull/431#issuecomment-1260875619) where I describe why the compare step output is correct for grabbing PAS and suggest how to also get dPAS coordinates (the above only grabs the pPAS coordinates which are the `changepoint`)
