### ISSUE TITLE
Question: what are you missing in the README in execution_workflows directory?

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#48]
The README should contain more precise information on how these execution workflows have to look like.    
Some open questions:    
- what exactly means preprocessing within execution wfs? NOT QC or adapter removal, as those will be done in nf-core/rnaseq
- test files for development (which are inputs, which are outputs, which to take?)
- naming convention for output files (`DATASET_NAME/METHOD_NAME/CHALLENGE_NAME.bed` ???)
- What should the outputs be? one file per sample? replicates aggregated?
- explain challenges, identifiers, etc.;
- what should the samples table in the snakemake template contain
- how should arguments to methods be handled (always use defaults, contact developers, interface all arguments?)
- if a method needs to be called differently for the different challenges, should that be done in one workflow or in separate ones?
- ...

# Please comment on this issue with any open questions you have about execution workflows, or with suggestions on standardizing and documenting the execution workflows!

**Comment by mkatsanto** [comment]
- missing samples.csv template in the snakemake template
- where should the output folder be?

**Comment by MelinaKlostermann** [comment]
- should we use a sample_sheet.csv as input? And are we allowed to change the columns of the sample sheets provided in e.g. the nextflow template? 
- and should we then also keep the CHECK_SAMPLESHEET process in the beginning of the main.nf?

**Comment by dominikburri** [comment]
> * missing samples.csv template in the snakemake template
> * where should the output folder be?

See for a working samples.csv here: https://github.com/iRNA-COSI/APAeval/blob/main/tests/pilot_benchmark/snakemake/configs/samples.csv 
It was left empty on purpose, because we didn't know what kind of input specific methods need. This gives flexibility on how to supply parameters. 

Output folders should be within the execution workflow, but right now we have no clear system yet (i.e. how to make it unique and findable etc. )

**Comment by MelinaKlostermann** [comment]
- where should additional parameters of the tools e.g p-value cut-off be defined? Also the sample sheet? Or in the .config file?

**Comment by dominikburri** [comment]
> * where should additional parameters of the tools e.g p-value cut-off be defined? Also the sample sheet? Or in the .config file?

I think this depends, for some parameters it makes sense to have them per sample, e.g. fragment length, and thus to have them in the sample sheet.
Other parameters are fix for a particular dataset, e.g. strandedness, and thus make more sense in the config file. 

Maybe others have a different opinion about this?

**Comment by ninsch3000** [comment]
Agree with Dominik: all parameters that are *sample specific* go into the samples table, all that are *run-/dataset specific* into the config.

**Comment by EuancRNA** [comment]
What does [IDENTIFIER] mean in the workflow file (In my case a Snakefile) and what should I put for it?
