### ISSUE TITLE
Test data: Should ground truth comply with execution workflow output specification?

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#49]
The provided [ground truth test files](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data) have number of reads in score column, instead of tpm as specified in the [APAeval execution workflow output specification](https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/execution_output_specification.md). 
- Might this be confusing or misleading for hackers, because the output of execution wfs has to contain tpm? 
- Might this hinder testing of summary workflows?
- Or is it on purpose that ground truth and execution wf outputs have different formats?

**Comment by mrgazzara** [comment]
This is a great point. I reduced the test data file sizes to take up less space (2 genes instead of 100 genes) and with this commit (e141a87)  I changed the ground truth files to have TPM values instead of raw reads.
