### ISSUE TITLE
I3: Specification - Percent of genome-wides sites identified

### ISSUE THREAD

**Issue by mfansler** [iRNA-COSI/APAeval#5]
Create specification for I3.

**Working definition:** Compare output of tool's RNA-seq-based site identification to established atlas(es) of polyadenylation sites (PolyASite, PolyA_DB, GENCODE, RefSeq).

**Notes:** This would be a measure of what percent of sites identified are near (within a fixed window) of a database's sites.

**Comment by mzavolan** [comment]
If the prediction methods provide scores for the sites that they predict, the area under the ROC can also be calculated as a measure of prediction accuracy.
