### ISSUE TITLE
Data processing: Upload A-seq2 HEK293 ground truth data

### ISSUE THREAD

**Issue by mrgazzara** [iRNA-COSI/APAeval#53]
We need the bed files with TPMs from the A-seq2 pipeline of the 6 HEK293 samples 

I've made a directory in the APAeval Google Drive for initial uploading and sharing of the "ground truth"/orthogonal 3'end data so you can upload those here: [https://drive.google.com/drive/folders/1bbESWHzHG7Wv3Bk2FmNnateFophBuP8u?usp=sharing](https://drive.google.com/drive/folders/1bbESWHzHG7Wv3Bk2FmNnateFophBuP8u?usp=sharing)

Uploading based on the PAS cluster coordinates (instead of a single nucleotide) should be okay for now.

**Comment by ninsch3000** [comment]
Did those with Ensembl Homo_sapiens.GRCh38.87.gtf and Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
I guess I should re-run with the genome and annotation we decide on? Have you decided already?

**Comment by mrgazzara** [comment]
Does the transcriptome annotation alter cluster calling / quantification? Not sure if that's 100% necessary. 

Regenerating the simulation data (based on [Gencode v26](https://www.gencodegenes.org/human/release_26.html)) would be very difficult so yes maybe that is best.

**Comment by ninsch3000** [comment]
Uploaded one bed file per sample, columns 
chr | cluster start | cluster stop | ID(chr:representative site:strand) | TPM | strand |
representative site is the one with highest expression within the cluster.

Mapping done with STAR to Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa (Ensembl). Chromosomes thus labeled '1,2,...'
