### ISSUE TITLE
Data Processing: diffUTR mouse simulation data with nf-core 

### ISSUE THREAD

**Issue by mrgazzara** [iRNA-COSI/APAeval#54]
@plger previously generated mouse simulation data for his work on diffUTR [Gerber et al. 2021](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04114-7)

There are 6 fastq.gz files uploaded to figshare [https://figshare.com/articles/dataset/diffUTR_simulation/13726143](https://figshare.com/articles/dataset/diffUTR_simulation/13726143) that we will need to align these files to mm10 using the nf-core RNA-seq workflow.

**Comment by faricazjj** [comment]
dataset dropped, changed to P19
