### ISSUE TITLE
Data Processing: create ground truth from Mayr 3'end seq samples

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#57]
In order to be able to use the [primary immune cell data](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE111310) we'll have to process the available 3'end seq data from this study.
Starting point for creating a workflow could be the rules for `3'-Seq (Mayr)` from the [PolyASite workflow](https://github.com/zavolanlab/polyAsite_workflow). However, an additional processing step which removes highly abundant immunoglobulin reads, as described in the [publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5928244/), might have to be included (Attaching the corresponding paragraph from the Methods section of the publication)
[mayr_primary_immune_cells_processing.txt](https://github.com/iRNA-COSI/APAeval/files/6555284/mayr_primary_immune_cells_processing.txt)

**Comment by BenNicolet** [comment]
Yes the PolyASite sounds like the way to go. 
For the Ig-transcripts, in my experience it is mostly problematic with plasmablast. Naive B cells have relatively few Ig-tx being expressed. I think for the Mayr paper mentioned above, it was important to filter out the Ig-genes to allow for quantification and comparison with other populations. 
I dont think it would matter much for us in our case where we want to identify and quantify (whether it is Ig-genes or other genes). no?
