### ISSUE TITLE
Put input files in S3 bucket

### ISSUE THREAD

**Issue by uniqueg** [iRNA-COSI/APAeval#61]
Put all (currently available) input files into AWS S3 bucket `s3://rnasoc-scratch-us-east-1` under prefix `input_files`.

Generally, the procedure to set up `aws-cli` and interact with an s3 bucket is described in [this guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html). See below for a detailed description of all of the steps that need to be taken:

- [x] Ask Alex to DM you the access keys
- [x] Install AWS CLI (follow the [corresponding link](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html) in the guide above)
- [x] Setup AWS CLI credentials via the keys obtained from Alex (follow the [Configuration Basics](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html) link in the guide above)
- [x] Create an empty directory; move inside that directory and create a subdirectory `input_files`, then copy all files that you want to upload into that subdirectory; make sure that you are still in the original directory you created and that this directory only contains the single subdirectory `input_files`
- [x] Upload all files to s3 with the following command: `aws s3 sync . s3://rnasoc-scratch-us-east-1`; if the files were organized as described before, all files in the directory `input_files` will be created in the s3 bucket under the prefix `input_files`
- [x] Verify that all files (now more accurately _objects_) are available in the bucket by running `aws s3 ls s3://rnasoc-scratch-us-east-1/input_files --recursive`
- [x] Also verify that you can download a file with `aws s3 get-object s3://rnasoc-scratch-us-east-1/input_files/{name_of_file_you_want_to_download}`
- [x] Create a table that lists all input files, descriptions of the files and their s3 URIs
- [x] Share the table in channels #general and #data

**Comment by uniqueg** [comment]
I've tried to upload a test file and the access keys I got don't seem to have the permissions required to put objects in the buckets. Need to figure this out first, so the issue is blocked in the meantime

**Comment by mrgazzara** [comment]
Note to download the file I had to use a slightly different command than the example:

`aws s3api get-object --bucket rnasoc-scratch-us-east-1 --key input_files/{name_of_file_you_want_to_download}`

Using version:
```console
mgazzara@naxos4:~$ aws --versrion
aws-cli/2.2.7 Python/3.8.8 Linux/4.15.0-143-generic exe/x86_64.ubuntu.18 prompt/off
```

`$ aws --version`
`aws-cli/2.2.7 Python/3.8.8 Linux/4.15.0-143-generic exe/x86_64.ubuntu.18 prompt/off`

**Comment by mrgazzara** [comment]
I've created a Google Sheet in the APAeval Google Drive to keep track of the s3 URIs with their descriptions:

[https://docs.google.com/spreadsheets/d/10nc4D6dg5lZNi-o8O3MMSWaimqo6hRuDiNUflzeWBuI/edit?usp=sharing](https://docs.google.com/spreadsheets/d/10nc4D6dg5lZNi-o8O3MMSWaimqo6hRuDiNUflzeWBuI/edit?usp=sharing
