### ISSUE TITLE
Matching up predicted with ground truth sites

### ISSUE THREAD

**Issue by mzavolan** [iRNA-COSI/APAeval#64]
Both for identification and for quantification we need to identify which ground truth site corresponds to each predicted site, if a 'site' is not a single base. We assume that ground truth sites, whether single position or interval, are correct and non-overlapping. The script should take as input bed files for both predicted and ground truth data, as well as a distance parameter, specifying by how many nucleotides should the predicted sites be extended to the  left and right. Predicted sites that overlap can be merged and their expression summed up. For each predicted site/cluster the group truth sites that overlap with it can then be identified. If a predicted site/cluster overlaps with more than one ground truth cluster,  it can be assigned to each of the overlapping ground truth sites with a fractional weight. This could be calculated as the number of overlapping nucleotides divided by the length of the predicted site/cluster. The expression can assigned proportionally to these weights. 

To have the full information for  computing various metrics the output should contain:
* 1. ID, start and end of predicted site
* 2. ID, start and end of overlapping ground truth site
* 3. weight with which the predicted site was assigned to the ground truth site
* 4. expression of the predicted site assigned to the ground truth site
* 5. expression level of ground truth site

**Comment by mfansler** [comment]
Related: #8 and #9

**Comment by mrgazzara** [comment]
After our discussion @ninsch3000 found [bedtools window](https://bedtools.readthedocs.io/en/latest/content/tools/window.html) as a promising approach to accomplish the distance based overlaps between BED files.
