### ISSUE TITLE
Add All Contributors app

### ISSUE THREAD

**Issue by uniqueg** [iRNA-COSI/APAeval#71]
Nice way to have everyone's code contributions tracked more prominently: https://allcontributors.org/

**Comment by chelseaherdman** [comment]
@all-contributors please add @chelseaherdman @FitzsimmonsCM for projectManagement

**Comment by mrgazzara** [comment]
@all-contributors please add @chelseaherdman @FitzsimmonsCM for projectManagement

**Comment by mrgazzara** [comment]
Looks like it's working. Have at it @FitzsimmonsCM , @chelseaherdman !

**Comment by FitzsimmonsCM** [comment]
Thanks @mrgazzara
