### ISSUE TITLE
Question: Does your method require special STAR settings?

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#73]
Will you need specific or non-standard information from the `.bam` tags in order to run your method?

**Comment by chilampoon** [comment]
IsoSCM needs this param `--outSAMstrandField intronMotif`

**Comment by faricazjj** [comment]
Out of all the tools we have, only IsoSCM requires special STAR setting (xs tag) and STAR is currently included as part of IsoSCM workflow

**Comment by faricazjj** [comment]
Discussed with @ninsch3000 and @SamBryce-Smith, closing this issue since STAR for IsoSCM is already incorporated as part of the workflow, no other tools require STAR, and no action is currently needed to be done on the input samples
