### ISSUE TITLE
Kamikaze Pilot: Decide on one dataset

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#78]
Which dataset with corresponding ground truth is ready to go? 
How do execution workflows have to be run on that? (If in doubt, would an individual sample (that has a ground truth) be a good start?
To Do:
* [x] choose a dataset suitable for the Kamikaze Pilot benchmark (#77)
* [x] create a [param code](https://github.com/iRNA-COSI/APAeval/blob/main/summary_workflows/parameter_codes.md) (#75)
* [x] communicate availability (also for genome/annotation files) to the hackers, along with instructions on what to take care of
* [x] update this issue description

# param code
Work in progress discussion at [PR93](https://github.com/iRNA-COSI/APAeval/pull/93). Also available on [GDrive sheet](https://docs.google.com/spreadsheets/d/1iZ-4RknIfLsfBJ8ank6w9JrkeVq0PEvoeLbtKUwghmA/edit#gid=2058518990&range=A1)
# data availability s3 bucket
Mapping of accession numbers, sample names, and s3 URI links to input `bam` and ground truth `bed` files consistent with the `param code` is in below table (may be updated as Nextflow Tower executions finish). Also available on [GDrive sheet](https://docs.google.com/spreadsheets/d/1iZ-4RknIfLsfBJ8ank6w9JrkeVq0PEvoeLbtKUwghmA/edit#gid=842626470&range=A1)
| accession  | sample\_name   | s3\_uri                                                                              | file\_type    |
| ---------- | -------------- | ------------------------------------------------------------------------------------ | ------------- |
| SRR6795718 | Mayr\_CD5B\_R3 | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795718.bam                      | bam\_noChr    |
| SRR6795719 | Mayr\_CD5B\_R4 | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795719.bam                      | bam\_noChr    |
| SRR6795720 | Mayr\_NB\_R1   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795720.bam                      | bam\_noChr    |
| SRR6795721 | Mayr\_NB\_R2   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795721.bam                      | bam\_noChr    |
| SRR6795723 | Mayr\_NB\_R3   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795723.bam                      | bam\_noChr    |
| SRR6795724 | Mayr\_NB\_R4   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795724.bam                      | bam\_noChr    |
| SRR6795725 | Mayr\_NB\_R5   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795725.bam                      | bam\_noChr    |
| SRR6795722 | Mayr\_NB\_R6   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795722.bam                      | bam\_noChr    |
| SRR6795726 | Mayr\_M\_R2    | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795726.bam                      | bam\_noChr    |
| SRR6795727 | Mayr\_M\_R6    | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795727.bam                      | bam\_noChr    |
| SRR6795713 | Mayr\_GC\_R2   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795713.bam                      | bam\_noChr    |
| SRR6795714 | Mayr\_GC\_R4   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795714.bam                      | bam\_noChr    |
| SRR6795715 | Mayr\_GC\_R1   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795715.bam                      | bam\_noChr    |
| SRR6795716 | Mayr\_GC\_R3   | s3://rnasoc-scratch-us-east-1/mayr\_bams/no\_chr/SRR6795716.bam                      | bam\_noChr    |
| SRR6795684 | Mayr\_CD5B\_R3 | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_CD5B\_R3.SRR6795684.3seq.hg38.bed | ground\_truth |
| SRR6795685 | Mayr\_CD5B\_R4 | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_CD5B\_R4.SRR6795685.3seq.hg38.bed | ground\_truth |
| SRR6795686 | Mayr\_CD5B\_R5 | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_CD5B\_R5.SRR6795686.3seq.hg38.bed | ground\_truth |
| SRR6795687 | Mayr\_CD5B\_R6 | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_CD5B\_R6.SRR6795687.3seq.hg38.bed | ground\_truth |
| SRR1005606 | Mayr\_NB\_R1   | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_NB\_R1.SRR1005606.3seq.hg38.bed   | ground\_truth |
| SRR1005607 | Mayr\_NB\_R2   | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_NB\_R2.SRR1005607.3seq.hg38.bed   | ground\_truth |
| SRR6795688 | Mayr\_NB\_R3   | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_NB\_R3.SRR6795688.3seq.hg38.bed   | ground\_truth |
| SRR6795689 | Mayr\_NB\_R4   | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_NB\_R4.SRR6795689.3seq.hg38.bed   | ground\_truth |
| SRR6795690 | Mayr\_M\_R1    | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_M\_R1.SRR6795690.3seq.hg38.bed    | ground\_truth |
| SRR6795691 | Mayr\_M\_R2    | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_M\_R2.SRR6795691.3seq.hg38.bed    | ground\_truth |
| SRR6795693 | Mayr\_GC\_R2   | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_GC\_R2.SRR6795693.3seq.hg38.bed   | ground\_truth |
| SRR6795692 | Mayr\_GC\_R1   | s3://rnasoc-scratch-us-east-1/ground\_truths/Mayr\_GC\_R1.SRR6795692.3seq.hg38.bed   | ground\_truth |

**Comment by BenNicolet** [comment]
For the choice of dataset: 
If the ground truth is needed, A) process the 3' data from the B cells dataset. B) if A not done, then use the processed data from the mouse cortex (Darnell, not P19)

**Comment by mrgazzara** [comment]
Updated description above to point to param file and data
