### ISSUE TITLE
Kamikaze Pilot: Pre-process dataset with nextflow tower/nf-core/rnaseq

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#79]
blocked by #77 #78
* [ ] make sure to consider STAR settings mentioned in #73
* [ ] update this issue description

**Comment by mrgazzara** [comment]
I have had trouble getting this pipeline to run with Nextflow Tower. I'm switching my efforts elsewhere for now but wanted to give some information here if someone else wants to take this up (like @uniqueg).

The input `samplesheet` for nf-core RNA-seq is on our bucket at: `s3://rnasoc-scratch-us-east-1/nfcore_samplesheets/samplesheet_mayr.csv`. A ONE SAMPLE csv is also at `s3://rnasoc-scratch-us-east-1/nfcore_samplesheets/samplesheet_mayr0.csv` if you want to start there as well.

Genome could be set to `GRCh38` in which case the pipeline uses the UCSC annotation from [iGenome](https://support.illumina.com/sequencing/sequencing_software/igenome.html). We were talking about using the Ensembl based genome / annotation which could be fed in as separate parameters. At minimum this requires a `fasta` and `gtf` file and the pipeline can figure out the other information. 

These files are also on our bucket as `s3://rnasoc-scratch-us-east-1/genome_resources/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz` for the `fasta` and `s3://rnasoc-scratch-us-east-1/genome_resources/genome_resources/Homo_sapiens.GRCh38.94.gtf.gz` for the `gtf`. Direct links to the FTP is also possible. 

Using the `--save_reference` parameter if the Ensembl annotation will be built as this can be used in the future.

**Comment by uniqueg** [comment]
Run completed. Did _not_ include the STAR setting, but shouldn't matter for stranded data (and all data are stranded)
