### ISSUE TITLE
Q2: Specification - Correlation to 3'-End Seq

### ISSUE THREAD

**Issue by mfansler** [iRNA-COSI/APAeval#8]
Create specification for Q2.

**Working definition:** Compute correlation coefficient between tool's quantification obtained RNA-seq and the quantification from the corresponding 3'-end sequencing dataset (for each pair of test datasets).

**Comment by mfansler** [comment]
This will require a window size specification. As a first pass, we could assume the ground truth defines the vector of sites. A method that does not have a site within the window of the site will have zero TPM for that site. So the penalty is limited to failure to assign reads at appropriate locations.

As a second pass, if a tool assigns expression to sites that are not within the window of a 3'-end-based site these could further be penalized. I.e., the vector of comparison is the ground truth plus additional sites by the tool.

Thoughts?

**Comment by mzavolan** [comment]
The correlation can be computed for the union of sites, assigning 0 TPM to site that are missing from one or the other of the two data sets.

It is possible that tools report multiple closely-spaced sites, and a procedure for mapping between sites in the two data sets will have to be defined, with the distance as a parameter.
