### ISSUE TITLE
Kamikaze Pilot: Write summary workflow for benchmark x

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#82]
blocked by #77 #78
* [ ] update this issue description

**Comment by lschaerfen** [comment]
We have one python script that takes the output of a given tool (with expression level information) and matches the pA sites to a second ground truth bed file. The output can then be passed to the indivisual quantification scripts, of which one is done. It calculates the correlation coefficient of prediction and ground truth quantification. But none of this has been reviewed or tested yet... PR is here: #66 

I guess these could already be chained together in nextflow to resemble a summary workflow? Downside is that this gives us only a single (corr. coeff.) value per method, so not very flashy for the presentation. Could show two of the methods as a scatter plot of expression values, maybe the best and worst performing one?
