### ISSUE TITLE
Kamikaze Pilot: Run summary workflow on OEB

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#84]
blocked by #83
* [ ] update this issue description

**Comment by mfansler** [comment]
@uniqueg I'm going to put notes for the summary workflow JSON files in this issue. Let me know what else is needed to help set up the definitions for OEB.

The challenge specifications define the following JSON outputs from the summary workflows:

## Quantification 
### Q2 (Spec. in progress: (#91))
This is the most likely one to get some data output.

**Example**
```json
{"correlation_coefficient": 0.56} 
```

**Plot: Expression Correlation (Bar Plot)**
x-axis: method
y-axis: `correlation_coefficient` value

## Identification
### I2 ([Spec][i2-spec])

**Example**
```json
{
  "sensitivity": [0.10, 0.16, 0.21, 0.27, 0.32, 0.38, 0.43, 0.49, 0.54, 0.60, 0.65],
  "FDR": [0.20, 0.26, 0.31, 0.37, 0.42, 0.48, 0.53, 0.59, 0.64, 0.70, 0.75]
}
```
**Plot: ROC Curve (Line Plot)**
x-axis: `FDR`
y-axis: `sensitivity`

Note that each pair corresponds to a window size 0-100 nt, steps of 10 nt.

### I3 ([Spec][i3-spec])

**Example**
```json
{
  "Precision": [0.10, 0.16, 0.21, 0.27, 0.32, 0.38, 0.43, 0.49, 0.54, 0.60, 0.65]
}
```
Note there are two JSON files to be output, one for comparing against PolyASite and one for PolyA_DB.

**Plot: Precision Curve (Line Plot)**
x-axis: Distance to Site (nt) - discrete values 0-200 nt, steps of 20 nt
y-axis: `precision`


### I4 ([Spec][i4-spec])

**Example**
```json
{
  "annotation_3utr": 0.22, 
  "annotation_5utr": 0.15, 
  "annotation_intron": 0.18,
  "annotation_cds": 0.21,
  "annotation_terminal_exon": 0.15,
  "annotation_intergenic": 0.25,
  "annotation_ds_1kb": 0.05,
  "annotation_ds_5kb": 0.06,
  "annotation_ds_10kb": 0.07
}
```

**Plot: Genomic Features (Stacked Bar Plot)**
x-axis: method
y-axis: `annotation_*` (stacked)

Feature type should be color coded.

## Resources Benchmarks
### I1 (#6), Q1 (#7), D1 (#13)

?

[//]: # (References)
  
[i2-spec]: https://github.com/iRNA-COSI/APAeval/blob/main/summary_workflows/identification/I2_benchmark/I2_benchmark_specification.md
[i3-spec]: https://github.com/iRNA-COSI/APAeval/blob/main/summary_workflows/identification/I3_benchmark/I3_benchmark_specification.md
[i4-spec]: https://github.com/iRNA-COSI/APAeval/blob/main/summary_workflows/identification/I4_benchmark/I4_benchmark_specification.md
