### ISSUE TITLE
Q3: Specification - Similarity of per-gene polyadenylation site distibutions

### ISSUE THREAD

**Issue by mfansler** [iRNA-COSI/APAeval#9]
Create specification for Q3.

**Working definition:** Distance between poly(A) site distributions from quantification and from the corresponding 3'end dataset calculated for each gene separately.

**Notes:** Could either be for all genes or a subset. Possibly with some threshold value to count genes with correct quantification. Whereas [Q2](#8) focuses on expression value, this measures site usage (values in [0,1]).

**Comment by mzavolan** [comment]
Could calculate the weighted Jaccard similarity of relative usage of all sites (from 3'-seq and RNA-seq). For each gene, after taking the union of all sites, the relative usage  of site i is calculated as TPM_i/sum_j(TPM_j) to yield vectors T = [t1,..,tn] and P[p1,..,pn] for the 3' end and RNA-seq based values. Similarity is then J = (sum_i min(ti,pi))/(sum_i max(ti, pi)).

The procedure for mapping sites between the two sets needs to be defined.
